name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 1 1,14,28 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test (main)
      run: make install

